[package]
name = "boris_shared"
version = "0.1.0"
edition = "2021"


[dependencies]

serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

la-arena = "0.3.1"

smallvec = { version="1.11.0", features = ["serde"] }
bitvec = { version="1.0.1", features = ["serde"] }
